---

title: "Cloud Foundry and Kubernetes" 
source_repo_name: "cf-and-k8s"
meta_description: "In this guide we'll explore how Cloud Foundry and Kubernetes work together, how they relate to each other, help you decide which workloads to run on which technology."