---

title: "Try Cloud Foundry" 
source_repo_name: "trycf"
meta_description: "Try Cloud Foundry from your laptop using a specific Cloud Foundry instance, like your company's Cloud Foundry instance or one of the many as-a-service providers."