---

title: "What is Cloud Foundry?" 
source_repo_name: "what-is-cf"
meta_description: "This tutorial covers the basics of the Cloud Foundry platform including: what it is, its role in technology organizations, ideal workloads, oss and the foundation, and contributors and users."