---
baseURL: "((source_repo_name))"
languageCode: "en-us"
title: "((title))"
theme: "hugo-whisper-theme"
themesDir: "themes"

pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength: 30

menu:
  main:
  - name: "Overview"
    url: "/docs"
    weight: 1
  - name: "Source"
    url: "https://github.com/cloudfoundry-tutorials/((source_repo_name))"
    weight: 2
  - name: "Tutorials"
    url: "https://tutorials.cloudfoundry.org"
    weight: 3


params:
  google_analytics_id: "UA-160449920-1"
  homepage_button_link: "/docs"
  homepage_button_text: "Start the Tutorial"
  #homepage_intro: "((homepage_intro))"
  # homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true
  homepage_meta_tags:
    meta_description: "((meta_description))"
    meta_og_title: "((title))"
    meta_og_type: "website"
    meta_og_description: "((meta_description))"
    meta_twitter_site: '@cloudfoundry'
    meta_twitter_creator: '@cloudfoundry'
  logo:
    mobile: "/images/logo-mobile.png"
    standard: "/images/logo.png"

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
